### POST - Adding new task
POST http://localhost:8080/api/tasks
Accept: application/json
Content-Type: application/json

{
  "title": "Title R1",
  "description": "Description R1",
  "completed": false
}

> {%
    client.global.set('id', response.body.id);
%}

### GET - Retrieval of the task by the ID of the most recently added one
GET http://localhost:8080/api/tasks/{{id}}
Accept: application/json
Content-Type: application/json

> {%
    client.global.set('id', response.body.id);
%}

### PATCH - Completion of the most recently added task
PATCH http://localhost:8080/api/tasks/{{id}}/complete
Content-Type: application/json
Accept: application/json

{ "completed": true }

### GET - Retrival of a task by the given ID
GET http://localhost:8080/api/tasks/d31e7306-2566-4f57-98bc-1ae2f206695c
Accept: application/json
Content-Type: application/json

### PATCH - Completion of a task for the given ID
PATCH http://localhost:8080/api/tasks/a9aae745-c7a2-4e15-b47f-4b2cf0b90116/complete
Content-Type: application/json
Accept: application/json

{ "completed": true }

### POST - Adding a new task multiple times; i=100..100+n
< {%
    request.variables.set("i", Array.from({ length: 10 }, (_, k) => k + 100));
%}
POST http://localhost:8080/api/tasks
Accept: application/json
Content-Type: application/json

{
  "title": "Title-{{i}}",
  "description": "Batch insert no.: {{i}}",
  "completed": false
}

### GET - Retrieval of a single page of data; RequestParams: pageNumber=0 pageSize=5
GET http://localhost:8080/api/tasks?pageNumber=0&pageSize=5
Accept: application/json
Content-Type: application/json

### DELETE - Removal of a task by ID -> 204 No Content
DELETE http://localhost:8080/api/tasks/73b67aeb-89d6-46e2-ba24-98f768e28593
Accept: application/json

### DELETE - Removal of non-existent task -> 404 Not Found
DELETE http://localhost:8080/api/tasks/00000000-0000-0000-0000-000000000000
Accept: application/json

### PATCH - Patch of a task by ID
PATCH  http://localhost:8080/api/tasks/a9aae745-c7a2-4e15-b47f-4b2cf0b90116
Accept: application/json
Content-Type: application/json

{
  "title": "Title-001",
  "description": "New description from patch.",
  "completed": false
}
